---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "hyku.web.name" . }}-in
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # unrestricted
spec:
  # tls:
  # - hosts:
  #   - {{ .Values.ingress.host }}
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - backend:
          serviceName: {{ template "hyku.web.name" . }}
          servicePort: 80
